#!/usr/bin/env bash

SPEAKERS="analog-output;output-speaker"
HEADPHONES="analog-output;output-headphones-1"

pactl list sinks | grep "Active Port: $SPEAKERS" > /dev/null
if [[ $? -eq 0 ]]; then
    pactl set-sink-port 2 "$HEADPHONES"
else
    pactl set-sink-port 2 "$SPEAKERS"
fi
